// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, 
    name, 
    username,
    email, 
    password,
    phone_number, 
    "address", 
    role
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, name, username, email, phone_number, address, password, role, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID          uuid.UUID
	Name        string
	Username    string
	Email       string
	Password    string
	PhoneNumber string
	Address     string
	Role        string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.PhoneNumber,
		arg.Address,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
UPDATE users
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL RETURNING id, name, username, email, phone_number, address, password, role, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, deleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const existUsernameorEmail = `-- name: ExistUsernameorEmail :one
SELECT username, email
FROM users
WHERE (username = $1 OR email = $2) AND deleted_at IS NULL
LIMIT 1
`

type ExistUsernameorEmailParams struct {
	Username string
	Email    string
}

type ExistUsernameorEmailRow struct {
	Username string
	Email    string
}

func (q *Queries) ExistUsernameorEmail(ctx context.Context, arg ExistUsernameorEmailParams) (ExistUsernameorEmailRow, error) {
	row := q.db.QueryRowContext(ctx, existUsernameorEmail, arg.Username, arg.Email)
	var i ExistUsernameorEmailRow
	err := row.Scan(&i.Username, &i.Email)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, "name", username, email, "password",phone_number, "address", "role", created_at, updated_at
FROM users
WHERE deleted_at IS NULL
`

type GetAllUsersRow struct {
	ID          uuid.UUID
	Name        string
	Username    string
	Email       string
	Password    string
	PhoneNumber string
	Address     string
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.PhoneNumber,
			&i.Address,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, "name", username, email, "password",phone_number, "address", "role", created_at, updated_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID          uuid.UUID
	Name        string
	Username    string
	Email       string
	Password    string
	PhoneNumber string
	Address     string
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.Address,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIDs = `-- name: GetUserByIDs :many
SELECT id, "name", username, email, "password",phone_number, "address", "role", created_at, updated_at
FROM users
WHERE id = ANY($1::uuid[]) AND deleted_at IS NULL
`

type GetUserByIDsRow struct {
	ID          uuid.UUID
	Name        string
	Username    string
	Email       string
	Password    string
	PhoneNumber string
	Address     string
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetUserByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetUserByIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserByIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserByIDsRow
	for rows.Next() {
		var i GetUserByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.PhoneNumber,
			&i.Address,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, "name", username, email, "password",phone_number, "address", "role", created_at, updated_at
FROM users
WHERE username = $1 AND deleted_at IS NULL
`

type GetUserByUsernameRow struct {
	ID          uuid.UUID
	Name        string
	Username    string
	Email       string
	Password    string
	PhoneNumber string
	Address     string
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.Address,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    "name" = $2,
    username = $3,
    email = $4,
    "password" = $5,
    "role" = $6,
    phone_number = $7,
    "address" = $8,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL RETURNING id, name, username, email, phone_number, address, password, role, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID          uuid.UUID
	Name        string
	Username    string
	Email       string
	Password    string
	Role        string
	PhoneNumber string
	Address     string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Role,
		arg.PhoneNumber,
		arg.Address,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
